
import BackButton from './BackButton.svg'
import Homelogo from './home1.svg'
import Notiflogo from './notif.svg'
import Orderlogo from './order1.svg'
import MiniCapucino from './MiniCapucino.png'
import Americano from './americano.png'
import Affocado from './affogato.png'
import Caramel from './caramel.png'
import Capucino from './capucino.png'
import Heart from './heart.svg'
import Share from './share.svg'
import Boba from './Boba.png'
import Coffee from './Coffee.png'
import Milkshake from './Milkshake.png'
import Juice from './Juice.png'
import Vector from './Vector.png'
import Booking from './Booking.png'
import Pay from './Payment.png'
import Profile from './Profile.png'
import Service from './Service.png'
import Exterior from './Exterior.png'
import Lengkap from './Lengkap.png'
import Mesin from './Mesin.png'
import Nano from './Nano.png'
import Salju from './Salju.png'
import Poles from './Poles.png'
import Price from './Price.png'
import Bca from './bca.png'
import Bni from './bni.png'
import Dana from './dana.png'
import Gopay from './gopay.png'
import Mandiri from './mandiri.png'
import Shoppe from './shoppe.png'
export {Price, Bca, Bni,Dana,Gopay,Mandiri,Shoppe,
    Booking, Pay, Profile, Service
    ,Americano,Affocado,Caramel,MiniCapucino,BackButton, Homelogo, Notiflogo, Orderlogo, Capucino, Heart, Share, Boba, Coffee, Milkshake, Juice, Vector, Exterior,
Lengkap, Mesin,Nano,Salju,Poles};

