import Splash from "./Splash";
import Login from "./Login";
import Register from "./Register";
import Home from "./Home";
import Notification from "./Notification";
import Order from "./Order";
import PaymentPage from "./PaymentPage";
import Buy from "./Buy";
import Service from "./Service";
export {PaymentPage,Splash, Login, Register, Home, Notification, Order, Buy, Service};